"""Create all tables from models

Revision ID: 4c590b23b1bb
Revises: 
Create Date: 2026-01-11 21:03:55.763219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '4c590b23b1bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
