"""create_tables

Revision ID: f20fcaaa40d8
Revises: 4c590b23b1bb
Create Date: 2026-01-31 17:25:28.624165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = 'f20fcaaa40d8'
down_revision = '4c590b23b1bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handovers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('room', sa.String(length=10), nullable=True),
    sa.Column('guest_name', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('followup', sa.Boolean(), nullable=False),
    sa.Column('promised', sa.Boolean(), nullable=False),
    sa.Column('promise_text', sa.Text(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.Column('shift', sa.String(length=1), nullable=True),
    sa.Column('due_date', sa.String(length=10), nullable=True),
    sa.Column('due_time', sa.String(length=5), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_handover_date', 'handovers', ['date'], unique=False)
    op.create_index('idx_handover_date_created', 'handovers', ['date', 'created_at'], unique=False)
    op.create_index(op.f('ix_handovers_date'), 'handovers', ['date'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_name'), 'people', ['name'], unique=False)
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('shift', sa.String(length=1), nullable=False),
    sa.Column('people', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_schedule_date', 'schedules', ['date'], unique=False)
    op.create_index(op.f('ix_schedules_date'), 'schedules', ['date'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_schedules_date'), table_name='schedules')
    op.drop_index('idx_schedule_date', table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_people_name'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_handovers_date'), table_name='handovers')
    op.drop_index('idx_handover_date_created', table_name='handovers')
    op.drop_index('idx_handover_date', table_name='handovers')
    op.drop_table('handovers')
    # ### end Alembic commands ###
